71 - GUI for writing rules and stories
buerokratt/Training-Module pull request #293
Opened 2023-11-12 20:02 UTC by baha-a

2023-11-13 10:03 UTC, 1AhmedYasser requested changes

2023-11-13 10:03 UTC, 1AhmedYasser commented on GUI/src/pages/Training/Stories/CustomNode.tsx
> +    payload: any,
Is it possible to avoid any type and provide the actual type instead

2023-11-13 10:03 UTC, 1AhmedYasser commented on GUI/src/pages/Training/Stories/FormNode.tsx
> +    payload: any;
Is it possible to avoid any type and provide the actual type instead

2023-11-13 10:03 UTC, 1AhmedYasser commented on GUI/src/pages/Training/Stories/IntentNode.tsx
> +    payload: any;
Is it possible to avoid any type and provide the actual type instead

2023-11-13 10:03 UTC, 1AhmedYasser commented on GUI/src/pages/Training/Stories/SlotNode.tsx
> +    payload: any;
Is it possible to avoid any type and provide the actual type instead

2023-11-13 10:04 UTC, 1AhmedYasser commented
Please Modify the `.gitignore` to add `tim-db`

2023-11-13 10:07 UTC, 1AhmedYasser commented
Could you also modify the `react-flow` screen to make its navigation more easier by adding `panOnScroll` like its done here https://github.com/buerokratt/Service-Module/pull/144/commits/ec325dc884506d0c0f9026a865acf26316448481 , just for easier navigation

2023-11-15 00:17 UTC, baha-a commented
@1AhmedYasser, All the requested modifications have been implemented. Kindly review the PR again.

2023-11-15 08:12 UTC, merged

2023-11-15 08:32 UTC, 1AhmedYasser reviewed
LGTM

2023-11-15 08:32 UTC, 1AhmedYasser commented
> @1AhmedYasser, All the requested modifications have been implemented. Kindly review the PR again.

LGTM