Add intents with rule page
buerokratt/Training-Module pull request #626
Opened 2024-08-07 10:05 UTC by joonasroosalung

New view for adding/editing intents, tied to stories

2024-08-14 09:11 UTC, yb-ng commented on GUI/src/pages/Training/Intents/index.tsx
> +      // queryRefresh(selectedIntent?.id || '');
commented code, consider removing

2024-08-14 09:23 UTC, SanderSepp requested changes

2024-08-14 09:23 UTC, SanderSepp commented on GUI/src/pages/Training/Intents/CommonIntents.tsx
> +  }, [intentParam]);
Can intentsFullList and commonIntents change? If so useEffect is not executed, is it intentional?

2024-08-14 09:26 UTC, yb-ng approved these changes

2024-08-14 10:18 UTC, SanderSepp commented on GUI/src/pages/Training/Intents/CommonIntents.tsx
> +  }, [intentParam]);
Discussed, all intentional.

2024-08-14 10:19 UTC, SanderSepp approved these changes

2024-08-14 10:53 UTC, SanderSepp approved these changes

2024-08-15 09:48 UTC, turnerrainer commented
> ## [![Quality Gate Failed](https://camo.githubusercontent.com/5333b8e2ff49bd5efdc6d2efd30ec08d7ac8d67c5e80190d03b6c2cb29a5de8b/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=buerokratt_Training-Module&pullRequest=626) **Quality Gate failed**
> Failed conditions ![](https://camo.githubusercontent.com/ee78c91cde137cf4668f72b8e1247dadaaeb117c99c74bed0f21b1681b517491/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [18.6% Duplication on New Code](https://sonarcloud.io/component_measures?id=buerokratt_Training-Module&pullRequest=626&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=buerokratt_Training-Module&pullRequest=626)

Will come back to it in later stage.

2024-08-15 09:48 UTC, merged